### PR TITLE
Backslash escape refactor

### PR DESCRIPTION
**Pull request by bterlson**
Implements backslash escaping and applies some refactorings/renames.

### CODE REVIEW

**Comment by domenic** [comment]
LGTM with nits. Amend those commits and do a `--ff-only` merge (no merge commits on this project!)

**Comment by bterlson** [comment]
I don't know why it's not showing me your comments in source. Did I do something wrong?

> Not a class; should not be capitalized. Probably just three separate variables would be fine...

You don't think namespaces should be capitalized? (Eg. Math).

> Update readme too? Or we can wait on that.

I am waiting to understand the grammar better before updating the readme.

**Comment by domenic** [comment]
> I don't know why it's not showing me your comments in source. Did I do something wrong?

Maybe check the individual commits?

> You don't think namespaces should be capitalized? (Eg. Math).

The whole concept of namespaces doesn't sit well with me :P. Thus the three-variables thing. (My thinking is vague, but goes something like: either it's small enough to not need encapsulation, like this example, or it's big enough it should be a separate module.)

> I am waiting to understand the grammar better before updating the readme.

Sounds good.

**Comment by bterlson** [comment]
74aca20

**Pull request closed without merging**
