### PR TITLE
Implement parsing of unordered lists.

### LINKED ISSUE #24: Support bulleted lists
There are many unordered lists in the spec. This would be helpful.

See also https://github.com/bterlson/ecmarkup/issues/22.

### PR DESCRIPTION
**Pull request by bterlson**
Supports bulleted lists in all contexts and hybrid lists as well. Fixes #24.

### CODE REVIEW

**Comment by domenic** [comment]
Needs moar tests:

- Mixed indentation levels (e.g. 1 then 2 then 5 then 3)
- Initial indentation greater than zero
- Omitting the space between `*` and the first character (I don't have a strong opinion on what should happen here)

**Comment by bterlson** [comment]
Mixed indentation is already tested in other files I think.

Omitting space after * will cause it to lex as a star format rather than a list item. This makes sense to me :)

**Comment by domenic** [comment]
Sure, just would be good to get them down for the future.

**Comment by bterlson** [comment]
Added more tests. G2G?

**Comment by domenic** [comment]
LGTM. Nit for the future: no periods in commit messages.

**Comment by bterlson** [comment]
What about elipses....

**Comment by bterlson** [comment]
9977c14

**Pull request closed without merging**
