### PR TITLE
Make scanning of comments lazy

### PR DESCRIPTION
**Pull request by bterlson**
Oddly enough I think this bug existed in the old implementation as well. One character fix (and many characters of tests :))

### CODE REVIEW

**Comment by domenic** [comment]
What was the bug exactly? E.g. what would that test have done before?

**Comment by bterlson** [comment]
The greediness of the comment regexp made the scanner consider the start of the comment as the first  in the input.

**Comment by bterlson** [comment]
Specifically in the tokenizer test there would be three tokens, foo, a comment, and baz.

**Comment by domenic** [comment]
Ah right, makes perfect sense. LGTM!

**Comment by domenic** [comment]
I'll merge and do a patch release.

**Comment by domenic** [comment]
Merged as b157e776bca2cc94ec7166e9652c608074fae5b3

**Comment by bterlson** [comment]
Heh, as I was attempting to push the same change. Thanks, though!

**Pull request closed without merging**
