### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by bterlson**
Going to be working on getting ecma262 rendering using the new EMD, so expect a few PRs over the next few weeks toward this goal :)

This adds some missing emu elements, and also handles comments similarly to commonmark.

### CODE REVIEW

**Comment by domenic** [comment]
This will need rebasing now that i moved all the test cases into one folder. Also if I manage to merge the readme update first then add the new opaque element there.

Commit message nits: no periods, CommonMark capitalization.

**Comment by bterlson** [comment]
I will rebase once we get the readme in :)

**Comment by bterlson** [comment]
Rebased, fixed commit message.

**Comment by domenic** [comment]
First commit needs readme updates (and remove the period)?

**Comment by bterlson** [comment]
Trying again :-P

**Comment by domenic** [comment]
Awesome. Still not super-happy about the comments interrupting lists but I guess we can wait until a user complains.

**Comment by bterlson** [comment]
And what happens when they do? Deviate from commonmark? :-P

**Comment by bterlson** [comment]
In general, though, if you're mixing HTML with hard-wrapping you're going to have a bad time.

**Comment by domenic** [comment]
Either that or one emu-alg wrapper around two ols.

**Pull request merged**
